"""Optional, read-only SCO routing diagnostic for the onboard Pi 3 controller.

No power, reset, pairing, profile or vendor write commands are issued. This is
an administrator installer diagnostic, not an audio service endpoint.
"""
import datetime
import json
from pathlib import Path
import re
import subprocess
import sys


MODEL_COMPATIBLE = "/proc/device-tree/compatible"
BLUETOOTH_COMPATIBLE = "/proc/device-tree/soc/serial@7e201000/bluetooth/compatible"
READ_COMMAND = ("/usr/bin/hcitool", "-i", "hci0", "cmd", "0x3f", "0x001d")
ADAPTER_COMMAND = ("/usr/bin/hciconfig", "hci0")
ROUTING_NAMES = {0: "pcm", 1: "hci_transport", 2: "codec", 3: "i2s"}


class DiagnosticError(Exception):
    """Only predefined, non-sensitive codes are included in the output."""


def parse_adapter(output):
    if not isinstance(output, str) or len(output) > 16384:
        raise DiagnosticError("adapter_unverified")
    if len(re.findall(r"(?m)^hci\d+:.*$", output)) != 1:
        raise DiagnosticError("adapter_unverified")
    if not re.search(r"(?m)^hci0:\s+Type:\s*Primary\s+Bus:\s*UART\s*$", output):
        raise DiagnosticError("adapter_unverified")
    addresses = re.findall(r"BD Address:\s*([0-9A-Fa-f]{2}(?::[0-9A-Fa-f]{2}){5})(?=\s|$)", output)
    if len(addresses) != 1 or addresses[0].upper() in ("00:00:00:00:00:00", "FF:FF:FF:FF:FF:FF"):
        raise DiagnosticError("adapter_unverified")
    return {"name": "hci0", "address": addresses[0].upper(), "bus": "UART"}


def parse_read_response(output):
    """Accept exactly the event generated by Read_PCM_Configuration (0xFC1D).

    hcitool reads its first HCI event, which can belong to another command.
    Therefore its successful exit status alone does not validate this probe.
    """
    if not isinstance(output, str) or len(output) > 4096:
        raise DiagnosticError("response_unverified")
    match = re.fullmatch(
        r"\s*< HCI Command: ogf 0x3f, ocf 0x001d, plen 0\s*"
        r"> HCI Event: 0x0e plen 9\s+"
        r"((?:[0-9A-Fa-f]{2}\s+){8}[0-9A-Fa-f]{2})\s*",
        output,
    )
    if match is None:
        raise DiagnosticError("response_unverified")
    payload = bytes.fromhex(match.group(1))
    if payload[1:3] != b"\x1d\xfc":
        raise DiagnosticError("response_unverified")
    if payload[3] != 0:
        raise DiagnosticError("controller_read_rejected")
    return list(payload[4:])


def _run(runner, command):
    try:
        completed = runner(list(command), capture_output=True, text=True,
                           timeout=5, check=False, env={"LC_ALL": "C", "PATH": "/usr/bin:/bin"})
    except subprocess.TimeoutExpired:
        raise DiagnosticError("command_timeout") from None
    except PermissionError:
        raise DiagnosticError("permission_denied") from None
    except FileNotFoundError:
        raise DiagnosticError("command_unavailable") from None
    except (OSError, subprocess.SubprocessError):
        raise DiagnosticError("command_failed") from None
    if completed.returncode != 0:
        # Never include tool output: it is not needed to diagnose permission
        # failures and may include unrelated device information.
        if "Operation not permitted" in (completed.stderr or "") or "Permission denied" in (completed.stderr or ""):
            raise DiagnosticError("permission_denied")
        raise DiagnosticError("command_failed")
    return completed.stdout


def probe(runner=subprocess.run, read_bytes=None):
    if read_bytes is None:
        read_bytes = lambda path: Path(path).read_bytes()
    result = {
        "schemaVersion": 1,
        "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
        "outcome": "inconclusive",
        "adapter": {"name": "hci0"},
    }
    try:
        try:
            model = read_bytes(MODEL_COMPATIBLE).split(b"\0")
            controller = read_bytes(BLUETOOTH_COMPATIBLE).split(b"\0")
        except OSError:
            raise DiagnosticError("hardware_unverified") from None
        if b"raspberrypi,3-model-b" not in model or b"brcm,bcm43438-bt" not in controller:
            raise DiagnosticError("hardware_unverified")
        result["adapter"] = parse_adapter(_run(runner, ADAPTER_COMMAND))
        parameters = parse_read_response(_run(runner, READ_COMMAND))
        result.update(outcome="read", parameters=parameters,
                      routing=ROUTING_NAMES.get(parameters[0], "unknown"))
    except DiagnosticError as exc:
        result["error"] = str(exc)
    except Exception:
        # Optional installer diagnostics must never prevent installation, even
        # when a tool or the host returns an unexpected response shape.
        result["error"] = "diagnostic_failed"
    return result


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    if argv:
        result = {"schemaVersion": 1,
                  "timestamp": datetime.datetime.now(datetime.timezone.utc).isoformat(),
                  "outcome": "inconclusive", "adapter": {"name": "hci0"},
                  "error": "unsupported_arguments"}
    else:
        result = probe()
    print(json.dumps(result, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
